### ISSUE TITLE
negative numbers in CSS styles are not statically extracted

### ISSUE THREAD

**Issue by jantimon** [jantimon/next-yak#191]
When using negative numbers in styled components next-yak fails to statically extract them..  
So these numbers get converted to CSS variables and evaluated at runtime, even though they are constant values. This creates unnecessary overhead since these values could be inlined directly into the CSS

```tsx
const Button = styled.button`
  margin-top: ${-1}px;  // Gets converted to CSS variable
`;
```

Gets compiled to something like:

```tsx
const Button = styled.button(
  "Button_xyz", 
  { style: { "--marginTop": -1 } }
);
```

With CSS output:
```css
.Button_xyz {
  margin-top: var(--marginTop);
}
```

Since the negative number is a constant value, it should be inlined directly into the CSS:

```css
.Button_xyz {
  margin-top: -1px;
}
```
