### ISSUE TITLE
Add Changesets for Automated Release Management

### ISSUE THREAD

**Issue by jantimon** [jantimon/next-yak#197]
Currently managing releases of next-yak and yak-swc requires manual coordination

- Manually determining which packages need version bumps
- Ensuring proper version bumping when yak-swc (dependency) changes
- No changelog
- No standardized process for contributors to document their changes

We could add a tool like [Changesets](https://github.com/changesets/changesets) to automate the release workflow

The workflow becomes:

1. Make changes to code
2. Run `pnpm changeset`
3. Answer simple prompts about changes:
   ```
   🦋 Which packages would you like to include? ...
   🦋 Which type of change is this for next-yak? (major/minor/patch)
   🦋 Please enter a summary for this change:
   ```
4. Commit both code and generated `.changeset/*.md` file
5. Create PR

That's it! The changeset file serves as both release documentation and instructions for version bumping.

The Release workflow becomes also easier
1. Review PRs as normal, with added context from changeset files
2. Merge approved PRs to main
3. Automated GitHub Action will:
   - Create/update a Release PR aggregating all changesets
   - Show all version bumps and changelog changes
   - Handle the dependency relationship between yak-swc and next-yak automatically
4. Review and merge the Release PR when ready
5. Automated publishing to npm for both packages (not 100% sure if there is a secure way for that)

**Comment by Mad-Kat** [comment]
Long overdue :D 

Could we also add the CI/CD pipeline step to create a github release? That would pop up in the feed of other people and I think is generally a good practice to have. Wdyt?

**Comment by jantimon** [comment]
Absolutely - GitHub releases would be great - also for notifications and when searching for (breaking) changes 

I hesitated to implement automated npm publishing from CI because of the npm token - My fear was that a malicious PR running in our pipeline could potentially extract it..

Maybe we can ask @mjwrona about his thoughts?

Do you maybe know a repository which already does it really well?

**Comment by Mad-Kat** [comment]
Nextjs does it this way: [https://github.com/vercel/next.js/actions/runs/11637084876/workflow](https://github.com/vercel/next.js/actions/runs/11637084876/workflow)
Jotai is a bit simpler: [https://github.com/pmndrs/jotai/actions/runs/11345038973/workflow](https://github.com/pmndrs/jotai/actions/runs/11345038973/workflow)
Vite is similar: [https://github.com/vitejs/vite/actions/runs/11626702159/workflow](https://github.com/vitejs/vite/actions/runs/11626702159/workflow)
SWC: [https://github.com/swc-project/swc/actions/runs/11605345082/workflow](https://github.com/swc-project/swc/actions/runs/11605345082/workflow)

Looks like creating a special token just for publishing and storing it in the github secrets is what all the others do.

**Comment by jantimon** [comment]
Good news - I found a secure way to handle the npm tokens

We can use GitHub deployment environments which let us restrict secret access to protected branches only:

https://docs.github.com/en/actions/managing-workflow-runs-and-deployments/managing-deployments/managing-environments-for-deployment#deployment-branches-and-tags

When using "Protected branches only" mode, "only branches with branch protection rules enabled can deploy to the environment". This means a malicious PR can't access our npm token since their branch isn't protected.
And there is no way to trick it via workflow modifications

**Comment by jantimon** [comment]
To use Environments in Workflows we can specify like this:

https://docs.github.com/en/actions/writing-workflows/workflow-syntax-for-github-actions#jobsjob_idenvironment

Here is an example which uses `environment: production`

```
name: Deploy to NPM

on:
  push:
    tags:
      - 'v*'

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          registry-url: 'https://registry.npmjs.org'
      
      - name: Install dependencies
        working-directory: packages/next-yak
        run: npm ci
      
      - name: Build package
        working-directory: packages/next-yak
        run: npm run build
      
      - name: Publish to NPM
        working-directory: packages/next-yak
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npm publish --access public
```
