### ISSUE TITLE
optional optimization: reduce css class names

### ISSUE THREAD

**Issue by jantimon** [jantimon/next-yak#50]
given the follwing example:

```tsx
const Button = styled.button`
    @media (max-width: 768px) {
        ${props => props.primary ? css`
            background: palevioletred;
            color: white;
        `: css`
            background: white;
            color: palevioletred;
        `}
    }
`;
```

here next-yak would extract the following css:

```css
.Button {
   @media (max-width: 768px) {
        &:where(.primary) {
            background: palevioletred;
            color: white;
        }
        &:where(.not-primary) {
            background: white;
            color: palevioletred;
        }
    }
}
```

however `.Button` owns not a single declaration so we could instead change it to:

```css
@media (max-width: 768px) {
        .Button-primary {
            background: palevioletred;
            color: white;
        }
        .Button-not-primary {
            background: white;
            color: palevioletred;
        }
}
```

this will improve the css selector performance and decrease the css & html size
