### ISSUE TITLE
Semicolons after template literal expressions should show error (or correct it)

### ISSUE THREAD

**Issue by Mad-Kat** [jantimon/next-yak#74]
When you have a semicolon after a template literal expression
```tsx
export const Input = styled.input<{$primary: boolean}>`
  ${({$primary}) => $primary && css`
    color: red;
  `};
  color: blue;
`;
```
next-yak should show you an error because it generates non valid CSS that ignores other styles.

```css
.Input {
  &:where(.primary_0) {
    color: red;
  }
;
  color: blue;
}
```
